name: TabLocation
version: 1.5
main: com.jewelexx.tablocation.TabLocation
api-version: 1.13
authors: [jewelexx]
description: Adds the players location to their tab name, so you can see where they are by pressing tab at any time
softdepend:
  - PlaceholderAPI
  - TAB
permissions:
  tablocation.hide:
    description: Hides your location from your name
    default: false
